//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::post::Entity as Post;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_role_relation::Entity as UserRoleRelation;
